name: Pull Request

on:
  push:
    branches: [ "main" ]
  workflow_call:
  workflow_dispatch:


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@v4
#    - uses: dorny/paths-filter@v3
#      id: filter
#      with:
#        filters: |
#          outerButNotInner:
#            - '!folder1/folder2/**'
#          inner:
#            - 'folder1/folder2/**'
#
#    - name: inner was changed but not outer
#      if:  |
#        steps.filter.outputs.outerButNotInner == 'true'
#        && steps.filter.outputs.inner == 'true'
#      run: |
#        echo "you are not allowed"
#        exit 1

    - name: build-and-test    
      run: echo "MERGE"

  trigger-next:
    name: Trigger Next
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
#        env:
#          IMAGE_TAG: '${GITHUB_REF_NAME}.${GITHUB_SHA::8}'
        with:
          event-type: release-test
          client-payload: '{"image_tag": "`echo ${GITHUB_REF_NAME}.${GITHUB_SHA::8}`"}'
