run-name: Release Test - ${{ inputs.IMAGE_TAG }}

on:
  workflow_call:
    inputs:
      DISCO_ENVIRONMENT:
        required: true
        type: string
      BAKERY_ENVIRONMENT:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string

env:
  SERVICE_NAME: disco-frontend
  IMAGE_TAG: ${{ inputs.IMAGE_TAG }}

jobs:
  mock:
    name: Mock
    environment: ${{ inputs.DISCO_ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - name: Mock
        run: echo ${{ inputs.IMAGE_TAG }}

#  deploy-bakery:
#    name: Deploy Bakery
#    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
#    environment: ${{ inputs.DISCO_ENVIRONMENT }}
#    runs-on: "ubuntu-latest"
#    steps:
#      # Update Image Tag in disco-gitops
#      - name: Update Image Tag
#        uses: volvo-cars/volvo-common-workflows/deployments/update-image-tags@main
#        with:
#          repository: 'volvo-cars/disco-gitops'
#          path: '${{ env.SERVICE_NAME }}/overlays/${{ inputs.DISCO_ENVIRONMENT }}'
#          image_name: 'ghcr.io/volvo-cars/${{ env.SERVICE_NAME }}'
#          image_tag: ${{ env.IMAGE_TAG }}
#          token: ${{ secrets.GITOPS_GITHUB_PAT }}

#  validate-deployment:
#    name: Validate Deployment
#    needs: deploy-bakery
#    uses: ./.github/workflows/validate_deployment.yml
#    with:
#      BAKERY_ENVIRONMENT: ${{ inputs.BAKERY_ENVIRONMENT }}
#    secrets: inherit
#
#  annotate-grafana:
#    name: Annotate Grafana
#    needs: validate-deployment
#    uses: ./.github/workflows/annotate_grafana.yml
#    with:
#      MESSAGE: ${{ env.IMAGE_TAG }}
#      BAKERY_ENVIRONMENT: ${{ inputs.BAKERY_ENVIRONMENT }}
#    secrets: inherit
