name: Release Prod

on:
  repository_dispatch:
    types: [release-prod]
  workflow_dispatch:
    inputs:
      image_tag:
        default: ''
        type: string
        required: false
        description: The short sha (8 first characters) of the commit to deploy, leave empty to deploy the latest commit.

jobs:
  set-image-tag:
    name: Set Image Tag
    runs-on: ubuntu-latest
    outputs:
      output_image_tag: ${{ steps.set-output.outputs.output_image_tag }}
    steps:
      - name: debug
        run: echo ${{ github.event.outputs.output_image_tag }}

      - name: Set Manual Input as Image Tag
        if: "${{ inputs.image_tag != '' }}"
        run: echo "IMAGE_TAG=`echo ${{ inputs.image_tag }}`" >> $GITHUB_ENV

      - name: Set Previous Output as Image Tag
        if: "${{ inputs.image_tag == '' && github.event.client_payload.image_tag != '' }}"
        run: echo "IMAGE_TAG=`echo ${{ github.event.client_payload.image_tag }}`" >> $GITHUB_ENV

      - name: Set Last Commit on Current Branch as Image Tag
        if: "${{ inputs.image_tag == '' && github.event.client_payload.image_tag == '' }}"
        run: echo "IMAGE_TAG=`echo ${GITHUB_REF_NAME}.${GITHUB_SHA::8}`" >> $GITHUB_ENV

      - name: debug
        run: echo "IMAGE_TAG=${IMAGE_TAG}"

      - name: Set output
        id: set-output
        run: echo "output_image_tag=${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

  deploy:
    needs: set-image-tag
    name: Deploy prod
    uses: ./.github/workflows/release_env.yml
    with:
      disco_environment: "prod"
      bakery_environment: "weu-prod"
      image_tag: ${{ needs.set-image-tag.outputs.output_image_tag }}
    secrets: inherit

#  create-release-tag:
#    needs: [ deploy ]
#    name: 'Release notes'
#    runs-on: 'ubuntu-latest'
#    steps:
#      - name: set date env
#        run: echo "NOW=$(date +'v%Y.%m.%d%H%M%S')" >> $GITHUB_ENV
#
#      - name: Create release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          gh release create "${{ env.NOW }}" \
#              --repo="$GITHUB_REPOSITORY" \
#              --title="${{ env.NOW }}" \
#              --target=${{ GITHUB.SHA }} \
#              --generate-notes
