# This works as a ternary operator but using && and || instead of ? and :
# Set dynamic name in gitHub actions UI
run-name: Release Prod - ${{ inputs.commit != '' && format('{0}.{1}', github.ref_name, inputs.commit) || github.event.client_payload.image_tag != '' && github.event.client_payload.image_tag || format('{0}{1}', 'No input - latest comit on ', github.ref_name) }}
name: Release Prod

on:
  repository_dispatch:
    types: [release-prod]
  workflow_dispatch:
    inputs:
      image_tag:
        default: ''
        type: string
        required: false
        description: The short sha (8 first characters) of the commit to deploy, leave empty to deploy the latest commit.

jobs:
  set-image-tag:
    name: Set Image Tag
    uses: ./.github/workflows/set_image_tag.yml
    with:
      manual_input: ${{ inputs.commit }}
      payload_input: ${{ github.event.client_payload.image_tag }}

  deploy:
    needs: set-image-tag
    name: Deploy prod
    uses: ./.github/workflows/release_env.yml
    with:
      disco_environment: "prod"
      bakery_environment: "weu-prod"
      image_tag: ${{ needs.set-image-tag.outputs.output_image_tag }}
    secrets: inherit

  create-release-tag:
    needs: [ deploy ]
    name: 'Release notes'
    runs-on: 'ubuntu-latest'
    steps:
      - name: set date env
        run: echo "NOW=$(date +'v%Y.%m.%d%H%M%S')" >> $GITHUB_ENV

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ env.NOW }}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${{ env.NOW }}" \
              --target=${{ GITHUB.SHA }} \
              --generate-notes
