name: name
run-name: I dont care

on:
  workflow_call:
    inputs:
      DISCO_ENVIRONMENT:
        required: true
        type: string
      BAKERY_ENVIRONMENT:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string

env:
  SERVICE_NAME: disco-frontend
  IMAGE_TAG: ${{ inputs.IMAGE_TAG }}

jobs:
  mock:
    name: Mock
    environment: ${{ inputs.DISCO_ENVIRONMENT }}
    runs-on: ubuntu-latest
    steps:
      - name: Mock
        run: echo ${{ inputs.IMAGE_TAG }}

