name: Release Test

on:
  repository_dispatch:
    types: [release-test]
  workflow_dispatch:
    inputs:
      commit:
        default: ''
        type: string
        required: false
        description: The short sha (8 first characters) of the commit to deploy, leave empty to deploy the latest commit.

jobs:
  set-image-tag:
    name: Set Image Tag
    runs-on: ubuntu-latest
    outputs:
        output_image_tag: ${{ steps.set-output.outputs.OUTPUT }}
    steps:
      - name: Set Image Tag
        id: set-image-tag
        run: |
          if [[ "${{ inputs.commit }}" != "" ]]; then
            IMAGE_TAG="${GITHUB_REF_NAME}.${{ inputs.commit }}"
          elif [[ "${{ github.event.client_payload.image_tag }}" != "" ]]; then
            IMAGE_TAG="${{ github.event.client_payload.image_tag }}"
          else
            IMAGE_TAG="${GITHUB_REF_NAME}.${GITHUB_SHA::8}"
          fi
          echo "OUTPUT=$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    needs: [set-image-tag]
    name: Deploy test
    uses: ./.github/workflows/release_env.yml
    with:
      disco_environment: "test"
      bakery_environment: "weu-dev"
      image_tag: ${{ needs.set-image-tag.outputs.output_image_tag }}
    secrets: inherit

  trigger-next:
    name: Trigger Next
    needs: [deploy, set-image-tag]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: release-qa
          client-payload: '{"image_tag": "${{ needs.set-image-tag.outputs.output_image_tag }}"}'
  create-release-tag:
    needs: [ deploy, set-image-tag ]
    name: 'Release notes'
    runs-on: 'ubuntu-latest'
    env:
      COMMIT: ''
    steps:
      - name: set date env
        run: echo "NOW=$(date +'v%Y.%m.%d%H%M%S')" >> $GITHUB_ENV
      - name: get sha from image tag
        run: |
          COMMIT=$(echo "${{ needs.set-image-tag.outputs.output_image_tag }}" | cut -d '.' -f 1)
          echo "COMMIT=$COMMIT" >> $GITHUB_ENV
      - name: debug
        run: echo $COMMIT