name: Release Test

on:
  repository_dispatch:
    types: [release-test]
  workflow_dispatch:
    inputs:
      image_tag:
        default: ''
        type: string
        required: false
        description: The short sha (8 first characters) of the commit to deploy, leave empty to deploy the latest commit.

jobs:
  set-image-tag:
    name: Set Image Tag
    runs-on: ubuntu-latest
    outputs:
        output_image_tag: ${{ steps.set-output.outputs.output_image_tag }}
    steps:
      - name: Set Image Tag
        id: set-image-tag
        run: |
          if [[ "${{ inputs.image_tag }}" != "" ]]; then
            IMAGE_TAG=${{ inputs.image_tag }}
          elif [[ ${{ github.event.client_payload.image_tag }} != "" ]]; then
            IMAGE_TAG=${{ github.event.client_payload.image_tag }}
          else
            BRANCH=${GITHUB_REF_NAME}
            VERSION=${GITHUB_SHA::8}
            IMAGE_TAG=${BRANCH}.${VERSION}

          echo $IMAGE_TAG
          echo output_image_tag=$IMAGE_TAG >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: [set-image-tag]
    name: Deploy test
    uses: ./.github/workflows/release_env.yml
    with:
      disco_environment: "test"
      bakery_environment: "weu-dev"
      image_tag: ${{ needs.set-image-tag.outputs.output_image_tag }}
    secrets: inherit

  trigger-next:
    name: Trigger Next
    needs: [deploy, set-image-tag]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: release-qa
          client-payload: '{"image_tag": "${{ needs.set-image-tag.outputs.output_image_tag }}"}'
