# This works as a ternary operator but using && and || instead of ? and :
# Set dynamic name in gitHub actions UI
run-name: Release Test - ${{ inputs.commit != '' && format('{0}.{1}', github.ref_name, inputs.commit) || github.event.client_payload.image_tag != '' && github.event.client_payload.image_tag || format('{0}{1}', 'No input - latest comit on ', github.ref_name) }}
name: Release Test

on:
  repository_dispatch:
    types: [release-test]
  workflow_dispatch:
    inputs:
      commit:
        default: ''
        type: string
        required: false
        description: The short sha (8 first characters) of the commit to deploy, leave empty to deploy the latest commit.

jobs:
  set-image-tag:
    name: Set Image Tag
    uses: ./.github/workflows/set_image_tag.yml
    with:
      manual_input: ${{ inputs.commit }}
      payload_input: ${{ github.event.client_payload.image_tag }}

  deploy:
    needs: [set-image-tag]
    name: Deploy test
    uses: ./.github/workflows/release_env.yml
    with:
      disco_environment: "test"
      bakery_environment: "weu-dev"
      image_tag: ${{ needs.set-image-tag.outputs.output_image_tag }}
    secrets: inherit

  trigger-next:
    if: github.ref_name != 'main'
    name: Trigger Next
    needs: [deploy, set-image-tag]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: release-qa
          client-payload: '{"image_tag": "${{ needs.set-image-tag.outputs.output_image_tag }}"}'

  create-release-tag:
    needs: [ trigger-next, deploy ]
    if: always() &&
      (needs.deploy.result == 'success') &&
      (needs.trigger-next.result == 'success' || needs.trigger-next.result == 'skipped')
    name: 'Release notes'
    runs-on: 'ubuntu-latest'
    steps:
      - name: set date env
        run: echo "NOW=$(date +'v%Y.%m.%d%H%M%S')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: get commit from image tag
        run: |
          COMMIT=$(echo "${{ needs.set-image-tag.outputs.output_image_tag }}" | cut -d '.' -f 2)
          SHA=$(git rev-parse $COMMIT)
          echo "SHA=$SHA" >> $GITHUB_ENV

      - name: debug
        run: echo $SHA