on:
  workflow_call:
    inputs:
        manual_input:
            required: true
            type: string
        payload_input:
            required: true
            type: string

jobs:
  set-image-tag:
    runs-on: ubuntu-latest
    outputs:
      output_image_tag: ${{ steps.set-output.outputs.OUTPUT }}
    steps:
      - name: Set Image Tag
        id: set-image-tag
        run: |
          # If commit is provided, use it
          if [[ "${{ inputs.commit }}" != "" ]]; then
            IMAGE_TAG="${GITHUB_REF_NAME}.${{ inputs.commit }}"
          
          # If triggered by a repository_dispatch event, use the image_tag from the payload
          elif [[ "${{ github.event.client_payload.image_tag }}" != "" ]]; then
            IMAGE_TAG="${{ github.event.client_payload.image_tag }}"
          
          # Otherwise, use the latest commit on the branch
          else
            IMAGE_TAG="${GITHUB_REF_NAME}.${GITHUB_SHA::8}"
          fi

          echo "OUTPUT=$IMAGE_TAG" >> $GITHUB_OUTPUT