on:
  workflow_call:
    inputs:
        manual_input:
            required: true
            type: string
        payload_input:
            required: true
            type: string

jobs:
  set-image-tag:
    runs-on: ubuntu-latest
    outputs:
      output_image_tag: ${{ steps.set-image-tag.outputs.OUTPUT }}
    steps:
      - name: debug
        run: | 
          echo "manual_input: ${{ inputs.manual_input }}"
          echo "payload_input: ${{ inputs.payload_input }}"
      - name: Set Image Tag
        id: set-image-tag
        run: |
          # If commit is provided, use it
          if [[ "${{ inputs.manual_input }}" != "" ]]; then
            IMAGE_TAG="${GITHUB_REF_NAME}.${{ inputs.manual_input }}"
          
          # If triggered by a repository_dispatch event, use the image_tag from the payload
          elif [[ "${{ inputs.payload_input }}" != "" ]]; then
            IMAGE_TAG="${{ inputs.payload_input }}"
          
          # Otherwise, use the latest commit on the branch
          else
            IMAGE_TAG="${GITHUB_REF_NAME}.${GITHUB_SHA::8}"
          fi
          echo $IMAGE_TAG
          echo "OUTPUT=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: debug
        run: |
          echo "${{ steps.set-image-tag.outputs.OUTPUT }}"